#!/bin/sh

if [ -z "$1" ]; then
    exit 1
fi

# Row output
echo "MAX\tMIN\tAVG\tSTD"

# Get the file to process
OUTFILE=$1

# Compute the maximum
MAX=$(< "$OUTFILE" sort -nr | head -1)
MIN=$(< "$OUTFILE" sort -n | head -1)
AVG=$(< "$OUTFILE" awk 'BEGIN {count=0} {count+=$0} END {print count/NR}')
STD=$(< "$OUTFILE" awk -v AVG="$AVG" 'BEGIN {sum=0} {sum=($0-AVG)^2} END {print sqrt(sum/NR)}')

# Row output
echo "$MAX\t$MIN\t$AVG\t$STD"
